// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXUeWvkkHBkCrZ1KDZk2HTsZ9uYMDw3w',
    appId: '1:751174768859:web:05bfbd19ebde67897294fe',
    messagingSenderId: '751174768859',
    projectId: 'ears-5b7a1',
    authDomain: 'ears-5b7a1.firebaseapp.com',
    storageBucket: 'ears-5b7a1.appspot.com',
    measurementId: 'G-NTHTDM5QZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm66aWK9vCPN3EpUwqcT72LOW97k_mLoA',
    appId: '1:751174768859:android:c806409fabcac3b37294fe',
    messagingSenderId: '751174768859',
    projectId: 'ears-5b7a1',
    storageBucket: 'ears-5b7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSy_tpsTKpkmK3rbbjNpUkr8CHsFpMbM',
    appId: '1:751174768859:ios:e3c6d3f10fd276117294fe',
    messagingSenderId: '751174768859',
    projectId: 'ears-5b7a1',
    storageBucket: 'ears-5b7a1.appspot.com',
    iosClientId: '751174768859-3b6p1qrlmtoa598t2k6ckgckomjacie0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ears',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSy_tpsTKpkmK3rbbjNpUkr8CHsFpMbM',
    appId: '1:751174768859:ios:3a952699a06af72b7294fe',
    messagingSenderId: '751174768859',
    projectId: 'ears-5b7a1',
    storageBucket: 'ears-5b7a1.appspot.com',
    iosClientId: '751174768859-kedouj14qlos071p13v225o2ajdca4ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.ears.RunnerTests',
  );
}
